setwd ("/DIR/CONTAINING/DATA_FILE")
dat = read.csv("DATA_FILE.csv", header = TRUE)
install.packages(tidyr)
install.packages(dplyr)
install.packages(ggplot2)
install.packages(Hmisc)
library(tidyr)
library(dplyr)
library(ggplot2)
library(Hmisc)
select(dat, energy, baryons, mesons)
datbar = aggregate(baryons ~ energy, data = dat, sum)
datmes = aggregate(mesons ~ energy, data = dat, sum)
combine = select(datmes, mesons)
datfinal = cbind(datbar, combine)
ggplot(datfinal, aes(x=energy)) + geom_point(aes(y=baryons), color="red") + geom_point(aes(y=mesons), color = "green")
ggplot(datbar, aes(x=energy, y=baryons)) + geom_point(color="red") +stat_summary(fun.data=mean_cl_normal) + 
  geom_smooth(method='lm',formula=y~x)
ggplot(datmes, aes(x=energy, y=mesons)) + geom_point(color="green") +stat_summary(fun.data=mean_cl_normal) + 
  geom_smooth(method='lm',formula=y~x)
